//Idioma Ingles - Textos y Mensajes
var ColumnasIN = eval( [
	{"id": "tramoTrans","nombreColumna":"TRANSFER SECTION","width":"9%"},
	{"id": "horaSalida","nombreColumna":"Departure","width":"9%"},
	{"id": "fechaSalida","nombreColumna":"Departure date","width":"9%"},
	{"id": "horaLlegada","nombreColumna":"ARRIVAL TIME","width":"10%"},
	{"id": "itinerario","nombreColumna":"STOPS","width":"10%"},
	{"id": "fechaLlegada","nombreColumna":"ARRIVAL date","width":"8%"},
	{"id": "descuentos","nombreColumna":"DISCOUNT","width":"8%"},
	{"id": "claseDeServicio","nombreColumna":"SERVICE","width":"15%"},	
	{"id": "pisos","nombreColumna":"BUS","width":"13%"},
	{"id": "linea","nombreColumna":"BUS LINE","width":"13%"},		
	{"id": "transbordo","nombreColumna":"TRANSFER","width":"8%"},	
	{"id": "tarifa","nombreColumna":"Fare","width":"12%"},
	{"id": "enl_tar", "nombreColumna":"Fare", "width":"12%"},
	{"id": "promocion","nombreColumna":"SPECIAL OFFERS","width":"8%"},
	{"id": "enl_prom", "nombreColumna":"SPECIAL OFFERS", "width":"8%"},
	{"id": "selecciona","nombreColumna":"CHOOSE","width":"13%"},
	{"id": "enl_sel", "nombreColumna":"CHOOSE", "width":"13%"},
	{"id": "secciones", "nombreColumna":"SECTIONS", "width":"13%"}
]);
// Textos "duros" en el codigo HTML
var txtIN = {
	'lblSalioMal':'Something went wrong, please try again',
	'lblGuardarCambios':'Save Changes',
	'PASO':'Step',
	'DE':'Of',
	'MSG_codigopromo':'The page will be reloaded',
	'ADisponible':'Seat Avalible',
	'AOcupado':'Seat Ocupied',
	'ASeleccionado':'Seat Selected',
	'SALIDA':'From',
	'REGRESO':'To',
	'REGISTRO':'Registration',
	'ASIENTOS':'Seats',
	'RESUMEN':'Summary',
	'PAGO':'Payment',
	'CONFIRMACION':'Confirmation',
	'fechaSalida':'Depart date',
	'horaSalida':'Departure time',
	'fechaLlegada':'Arrival Date',
	'horaLlegada':'Arrive Time',
	'fechaRegreso':'Return',
	'Horario':'Time', //*
	'Servicio':'Service',
	'Linea':'Bus company',
	'Costo':'Cost',
	'Itinerario':'Itinerary',
	'Selecciona':'Select',
	'NoHaySalidasParaCriterio':'There is no availability for this request, please try again with another date or type of passenger...',
	'VerCostos':'See costs',
	'EstaIntercambiandoNumOper':'You are exchanging operation numbers',
	'CostoTotal':'Total costs',
	'CamposRequeridos':'Requiered fields',
	'FormadePago':'Types of payment',
	'Efectivo':'Cash',
	'PagoconTarjeta':'Card payment',
	'Domicilio':'Address',
	'Ciudad':'City',
	'CodPostal':'Zip code',
	'RSCalle':'Street',
	'RSNumExt':'External Number',
	'RSNumInt':'Internal Number',
	'RSDelMpio':'Area / Municipality',
	'RSEstado':'State',
	'RSInfoAdicional':'Aditional info',
	'RSPromocion':'Promo Code',
	'RSCorreo':'eMail',
	'RSConvenio':'Agreement <br>Number',
	'RSNombre':'name',
	'RSApPaterno':'last name',
	'RSApMaterno':'last name',
	'RSNombreD':'Name & Middle Name',
	'RSApPaternoD':'Last Name (Father Family Surname)',
	'RSApMaternoD':'2nd Last Name (Mother Family Surname)',
	'RSApPaternoA':'Last name (Father)',
	'RSApMaternoA':'Last name (Mother)',
	//'RSSeparador':'»',
	'RSSeparador':String.fromCharCode(187),
	//'RSSeparador2':'|',
	'RSSeparador2':String.fromCharCode(124),
	'Pais':'country',
	'TelCasaOfic':'Phone number Home/Office',
	'CorreoElectronico':'email address',
	'IncluyaLada':' Please include your area code',
	'VerTermCondic':'Read terms, conditions',
	'FechadeRegreso':'Return date',
	'RegistrodePasajeros':'Passenger Registration',
	'Utiliza1erNomParaPasajeros':'Use the first name for all passengers',
	'Adulto':'Adult',
	'Menor':'Child',
	'Insen':'Senior',
	'Estudiante':'Student',
	'Profesor':'Teacher',
	'Maestro':'Teacher',
	'VerItinerario':'View',
	'OcultarItinerario':'hide',
	'AceptoTerminosCond':'I accepts',
	'Y':'and',
	'CaptureTxtComoEnImg':'Capture the text like is shown in the image',
	'RefrescarImagen':'Refresh image',
	'Dia':'Day',
	'Hora':'Time',
	'Origen':'Depart',
	'selectNoResultados':'No results found',
	'Destino':'Arrive',
    'OrigenMayus':'Departure',
	'DestinoMayus':'Destination',
	'DatosDelPasajero':'Passenger information',
	'DatosDel':'Information of ',
	'Pasajero':'Passenger',
	'Asiento':'Seat',
	'AsientoMayus':'Seat',
	'ViajedeRegreso':'Return trip info',
	'ViajedeSalida':'Outward trip info',
	'SelecAsientoSalidaSigPasaj':'Select the outward trip seat for the following passenger:',
	'SelecAsientoRegresoSigPasaj':'Select the return trip seat for the following passenger:',
	'AsientoOcupado':'Occupied Seat',
	'AsientoDisponible':'Available Seat',
	'AsientoSeleccionado':'Selected Seat',
	'Aviso':'Message',
	'PagoCanceladoB':'Payment Cancelled by user',
	'SeleccionaOtraFormaPago':'Select another payment method',
	'ViajeSencillo':'One way',
	'ViajeRedondo':'Round trip',
	'ViajeAbierto':'Open',
	'ClasedeServicio':'Service Class',
	'NumOperacion':'Operation number',
	'NIT':'NIT',
	'ContrasenaActual':'Curret pasword',
	'ContrasenaNueva':'New password',
	'ConfirmarContrasena':'Confirm password',
	'FechaInicial':'Initial date',
	'FechaFinal':'Final date',
	'SaldoaDepositar':'Depositbalance',
	'MontoenFicha':'Amount in the deposit order',
	'PresContinuarParaEmitirFicha':'Press &quot;Continue&quot; to emit the deposit order',
	'FichadeDeposito':'Deposit order',
	'AgenciaMayus':'Agency',
	'Banco':'Bank',
	'Sucursal':'Branch',
	'Cuenta':'Account',
	'NumReferInterbanc':'Interbank refence number',
	'CantidadaDepositar':'Amount to deposit',
	'DatosdeCompra':'Purchase information',
	'TiempoRestante':'Time remaining',
	'ParaCompletarPaso':'To complete this step',
	'SuSesionExpirara':'Your session will expire: &#191;Do you want to add more time?',
	'Ahorro':'Saving',
	'Promocion':'Promo',
	'Pasajeros':'Passengers',
	'GraciasporSuCompra':'Thanks for your purchase',
	'VentaBoletosAgencias':'Sale of tickets for agencies',
	'Agencia':'Agency',
	'Usuario':'User',
	'Administrador':'Manager',
	'Venta':'Sale',
	'BoletoAbierto':'Open Ticket',
	'Intercambio':'Exchange',
	'Cancelacion':'Cancelation',
	'CambiarContrasena':'Change password',
	'Saldos':'Balance',
	'Movimientos':'Movements',
	'CerrarSesion':'Close session',
	'AdministradorAgencias':'Manager agencies',
	'Nombre':'name',
	'Elegir':'Choose',
	'DiaMayus':'Day',
	'Inicio':'Initiation',
	'Fin':'End',
	'DiaActivo':'Active day',
	'NumTransacEmpresa':'Company transaction number ',
	'NumAutorizBanco':'Bank autorization number',
	'NumReciboBanco':'Bank receipt number',
	'RSPagadoEnBanco':'Paid in Bank',
	'RSSaldoConsumidoConvenio':'Balance consumed from agreement',
	'RSSaldoConsumidoVF':'Balance consumed from Loyalty Program',
	'Operacion':'Operation',
	'Tipo':'Type',
	'Monto':'Amount',
	'Descuento':'Discount',
	'ParaImpreBoletosenTaquilla':'To print your ticket at the ticket office, you should show a copy of an official and valid ID.',
	'PasajeroResumen':'Info',
	'textorequiere':'required fields',
	'pasaporte':'VISA',
	'totalMay':'Total',
	'formapago1':'Mexican credit card',
	'formapago2':'American credit card',
	'botonfiltro':'Search',
	'tipoviaje1':'One Way',
	'tipoviaje2':'Round Trip',
	'titulofiltros':'Book your trip',
	'origenfil':'From',
	'destinofil':'To',
	'fechasalidafil':'Depart',
	'fecharegresofil':'Return',
	'cargandoorides':'loading...',
	'telef':'Phone',
	'correop':'Email',
	'Nombrepas':'Passenger Name',
	'RSTarjetaBancaria':'Bank Card',
	'RSPuntosViajeroFrecuente':'Frecuent Traveler Points',
	'RSNumeroConvenio':'Agreement Number',
	'RSConvenio':'Agreement',
	'RSARedimir':'To Redeem',
	'RSPuntos':'Points',
	'RSAPagarBanco':'To Pay At Bank',
	'RSAPagar':'To Pay',
	'RSNumero':'Number',
	'RSPromocionInvalida':'Promo is invalid or does not exist',
	'RSConvenioInvalido':'Agreement Code is invalid or does not exist',
	'RSNIP':'NIP',
	'RSNIPInvalido':'NIP is invslid or member does not exist',
	'Totalres':'Total amount',
	'MontoIva':'Tax',
	'Montobruto':'Price',
	'TipoPasRes':'T. Passenger',
	'Veravisopriva':'Privacy Policy',
	'SeparadorTermyPriva':'and',
	'mensajebancoerrA':'Do not close the browser, your transaction is being processed.',
	'mensajebancoerrB':'If an error occurred, please call:',
	'mensajebancoerrC':'Your session number is:',
	'mensajebancoerrD':'Your card was:',
    'Costo_n':'Normal cost',
	'sencillo':'Single Decker',
	'doble':'Double Decker',
	'LeyendaVFCRM_1':'Name Frequent Flyer',
	'LeyendaVFCRM_2':'Membership Level',
	'LeyendaVFCRM_3':'Points Available',
	'TituloVenta':'Online sale',
	'SubtituloVentaCorridas':'Consult Schedules',
	'SubtituloPersonaliza':'Fill the form with your information',
	'SubtituloAsientos':'Select your seat',
	'SubtituloResumen':'Confirm and Pay',
	'SubtituloPago':'Make your payment',
	'SubtituloDetalle':'Purchase details',
	'MenuFiltro1':'Bus',
	'MenuFiltro2':'+ Hotel',
	'MenuFiltro3':'Consult Schedules',
	'tipoviajetitulo':'Type of trip',
	'BotonMaximaF':'Sing in to M&aacute;xima Distinci&oacute;n',
	'BotonAgenciaF':'Sing in as Agency',
	'BotonContinuar':'Continue',
	'BotonRegresar':'Back',
    'BotonConsultar': 'Search',
	'VFContrasena':'Password',
	'FiltroCorridasTipoViajeI1':'One way',
	'FiltroCorridasTipoViajeR1':'Return',
	'FiltroCorridasTipoViajeI2':'Trip',
	'FiltroCorridasTipoViajeR2':'Trip',
	'FiltroCorridasViaje':'Trip',
	'VFLoginnombre':'Welcome User Name',
	'VFLoginpuntos':'Points',
	'CorridasDe':'From',
	'CorridasA':'To',
	'CorridasFecha':'Depart',
	'ItinerarioTit':'Stops',
	'ItinerarioOD':'From/To',
	'ItinerarioFS':'Depart Date',
	'ItinerarioHS':'Departure',
	'ItinerarioFL':'Arrival Date',
	'ItinerarioHL':'Arrival',
	'ItinerarioCerrar':'Close',
	'CorridasBotondes':'See',
	'CorridasDescuentos':'Special offers',
	'LVPertenesco':'I belog to',
	'LVMiembro':'Member ID or eMail',
	'LVIngresar':'Sing in',
	'MVIngresar':'Sing in with',
	'MVIngresar2':'My trip',
	'PersonalizaVer':'See ',
    'PersonalizaTerminos':'terms and Conditions',
    'PersonalizaPoliticas':'Privacy Notice',
	'AsientosAgregar':'Add passenger',
	'ResumenMarca':'Bus line',
	'ResumenAutobus':'Bus',
	'ResumenFP':'Select your preferred payment method',
	'ResumenTPas':'Type of passenger',
	'ResumenTotal':'Total payable',
	'ResumenAhorro':'You saved',
	'ResumenIntCantNIP':', if you wish to pay with points, please enter your pin number and the amount of points to use in this transaction.',
	'ResumenPagar':'Pay',
	'ResumenCuentaPtos':'You have',
	'ResumenPtos':'Points',
	'DetalleGuardar':'Save boarding pass',
	'DetalleImprimir':'Print',
	'Amextitulo':'Fill the required information like this in your documentation.',
	'AmexMonto':'Amount to Pay',
	'AmexTarjeta':'Number card of Credit / Debit',
	'AmexSeguridad':'CVV',
	'Amexfv':'Expiration Date. Month / Year',
	'AmexNombre':"Name(s) of Cardholder",
	'AmexApellido':"Last Name of cardholder",
	'AmexDireccion':'Address of cardholder',
	'AmexTel':'Telephone of cardholder',
	'AmexCorreo':'eMail of cardholder',
	'MenuSuperiorDes':'Destinations',
	'MenuSuperiorBol':'Tickets',
	'MenuSuperiorProm':'Special offers',
	'MenuSuperiorBen':'Benefit of ETN and Turistar',
	'MenuSuperiorHor':'Schedules',
	'IntercambioOpePub':'Operation number(s)',
	'NombrePasI':'Passenger name',
	'OrigenI':'Depart',
	'DestinoI':'Arrive',
	'CorreoI':'eMail',
	'CostoI':'Fare',
	'ViajeIda':'Depart date',
	'ResumenBoletoAbierto':'Summary of Purchase and Payment',
	'paseAbordaje':'Release of Open Ticket',
	'EsperaVIP':'Waiting Room VIP',
	'ServicioABordo':'Service On Board',
	'SCharters':'Charters Schedules',
	'DatosViaje':'Travel Info',
	'UseAbierto':'Use your open ticket.',
	'ModIti':'Modify your itinerary',
	'CapturaCodigo':'Please enter the code shown below.',
	'BotonHorariosCom':'Buy',
	'AdvertenciaIntercambio':'At the itinerary changes with a cheaper cost, there won\'t be refunds or devolutions',
	'chatenlinea':'online',
	'TransCel':'Insert your Code Transfer',
	'atencionaclientes':'customer service',
	'NotaEscalasPopUp':'Note: The list shows local times and dates',
	'Refacturar':'This operation to exchange and was billed, your invoice is canceled, requires its new operation is billed?',
	'ntGuardaPase':'The operation number and the NIT of your boarding pass have been sent by email.',
	'ntGuardaPase2':'You can also save on your device by pressing the "Save Pass" button located at the bottom of this screen.',
	'ConfirmAbreSesion':'Are you sure, do you want to open session?',
	'CerrarSesionVta':'Close session',
	'AbrirSesionVta':'Open session',
	'ConfirmCierraSesion':'Are you sure, do you want to close session?',
	'CuadreCaja':'It\'s generated cash box&#33;&#33;',
	'detalleAhorro':'You Saved',
	'PCD':'PCD',
	'otraDiscapacidad':'PCD',
	'AdultoPlu':'Adults',
	'MenorPlu':'Children',
	'MaestroPlu':'Teachers',
	'EstudiantePlu':'Students',
	'TipoFormaPagoMixto':'This exchange can be paid only with',
	'EfectivoM':'Cash',
	'TarjetaM':'Card',
	'PuntosM':'Points',
	'TransferM':'Transfer',
	'RecargaCapcha':'Refresh $ Image',
	'DatoDetalle':'Detail',
	'TipoBol':'Ticket type',
	'datoEnlace':'with transfer',
	'datoEnlace1':'with transfer and Direct travel',
	'datoEnlace2':'Direct travel and with transfer',
	'datoTramo':'Section',
	'btnEnlace':'Choose this trip',
	'btnSelAsiento':'Choose your seat',
	'chViajaDirecto':'Direct travel',
	'btnDelDiag':'Delete',
	'titleViajesEnl':'Direct travel',
	'titleViajesTrn':'Transhipment travel',
	'QueEsPaypal':'What is Paypal?',
	'PaypalDes1':'It is a means easy , fast and secure payment.',
	'PaypalDes2':'You can make payments by credit card and debit cards.',
	'PaypalDes3':'Register PayPal your financial data in one go . You not need to Provide them in subsequent purchases.',
	'PaypalDes4':'More than 100 million people in the world use PayPal.',
	'PaypalDes5':'PayPal protects your information We do not share your financial data.',
	'ComoPagarCon':'How to Pay',
	'Envia': 'Send',
	'Confirma':'Confirm',
	'Recibiras':'You will receive',
	'Ingresa':'Enter',
	'TransfDes1':'text message to 4040 with the word Code (space) amount. Example. CODE 300 or through the APP transfer.',
	'TransfDes2':'Your Application Transfer Entering your PIN code.',
	'TransfDes3':'a transfer Banamex Code.',
	'TransfDes4':'your Transfer Code and checkout your bus tickets.',
	'VerifiqueDatos':'Check your data',
	'VerifiqueDatosAb':'Check your ticket Open Data',
	'PaseAbordar':'Your boarding pass',
	'FiltrosAgen':'Agencies filters',
	'FiltroAgenAb':'Open filter agencies',
	'RegistroBolA':'Registration open ticket data',
	'DatosIntercambio':'Data Exchange',
	'AdminAgencias':'Manager Agencies',
	'EligeHoSal':'Choose the departure schedule',
	'EligeHorIR':'Choose hours round trip',
	'EligeHorReg':'Choose the return schedule',
	'RegistroDatos':'Data register',
	'EligeAsiento':'Choose a Seat',
	'EligeAsIR':'Choose the seat round trip',
	'EligeAsRe':'Choose a return Seat',
	'titleCorSel':'Select your schedule',
	'taquillas':'Box Office',
	'titlewindow':'Required Information',
	'cantMaximaAdulto':'The maximum amount is 10 passenger ADULT',
	'cantMaximaMenor':'The maximum amount is 3 passenger CHILDREN',
	'cantMaximaInsen':'The maximum amount is 3 passenger SENIOR',
	'cantMaximaEst':'The maximum amount is 3 passenger STUDENT',
	'cantMaximaProf':'The maximum amount is 2 passenger TEACHER',
	'cantMaximaPCD':'The maximum amount is 1 passenger PCD',
	'HorarioViaje':'Travel Schedule',
	'titleEnlace':'Transfer',
	'boxTitleUser':'Personalize your search',
	'textHViaje':'All , Morning , Afternoon, Evening',
	'textEServicio':'All, Local, On the Way',
	'textCEscalas':'All, With Stops, Nonstop',
	'textTEnlaces':'All, With Transfer, Without Transfer',
	'textTAutobus':'All, Single, Double decker',
	'textCEmpresa':'All, ETN, Turistar',
	'btnEditDiag':'Edit',
	'btnAcepDiag':'Accept',
	'PrecioDatos':'Price with discount',
	'selSerMovil':'Select Service',
	'titleCRMMD':'M&Aacute;XIMA DISTINCI&Oacute;N',
	'titleCRMVM':'VIAJA M&Aacute;S',
	'btnIniciaSesion':'Log In',
	'titleCompraAqui':'Buy your bus tickets here&#33;',
	'RSEscriba':'writte your',
	'subtitleAg':'Purchase your bus Ticket',
	'titleLoginAgencia':'Enter your information and buy your bus tickets',
	'btnCompartirViaje':'Share your trip on Facebook',
	'txtCompartirViaje':'Click, if you want to share with your contacts traveling by ETN Turistar Lujo',
	'lblCompartirViaje':'Share my trip',
	'IngreseDatos':'Enter the following data',
	'lblMercadoPago':'MercadoPago Transaction ID',
	'lblPaypalPago':'Paypal Transaction ID',
	'lblEmailPaypalPago':'Client Paypal Email Account',
	'lblUsuariosAgencia':'Users Agency',
	'lblIntercambioBoleto':'Ticket Exchange',
	'lblCancelBoleto':'Cancellation of Tickets',
	'lblCambiarContra':'Change Password',
	'lblReportMovimientos':'Movement Report Agency',
	'lblSaldosAgencia':'Balances agencies',
	'lblSaldoDeposito':'Amount to deposit',
	'lblMontoFicha':'Amount in deposit sheet',
	'lblFichaDeposito':'Deposit form agency',
	'BotonEnviar':'Submit',
	'lblSesionesUsiario':'User sessions',
	'lblHeaderSesion':'No. Session',
	'lblHeaderFApertura':'Opening Date',
	'lblHeaderHApertura':'Opening Time',
	'lblHeaderFCierre':'Closing Date',
	'lblHeaderHCierre':'Closing Time',
	'lblHeaderCuadreCaja':'Cuadre Caja',
	'lblCapturaCuadreCaja':'Manual capture of cash register',
	'lblHeaderConcepto':'Concept',
	'lblHeaderValor':'Value',
	'MenuAutobus':'Buses',
	'MenuTipoAutobus':'Bus types',
	'MenuServabordo':'Service on Board',
	'MenuTerminales':'Terminals',
	'MenuSalaEspera':'Lobby',
	'MenuBoletos':'Bus tickets',
	'MenuTiposBoleto':'Types of ticket',
	'MenuPuntosVenta':'Ticket Office and Points of sale',
	'MenuAgenciasAfil':'Affiliated Agencies',
	'MenuCentroContacto':'Contact Center',
	'MenuOxxo':'Oxxo',
	'MenuPriceTravel':'Price Travel',
	'MenuBeneficios':'Benefits Costaline',
	'MenuAcerca':'About us',
	'MenuContacto':'Contact',
	'MenuPreguntas':'Frequent questions',
	'MenuBolsatrabajo':'Job Exchange',
	'MenuDondeComprar':'Where to buy?',
	'MenuPaqueteria':'Parcel service',
	'MenuRentaBus':'Bus rental',
	'MenuBusHotel':'Bus + Hotel',
	'MenuDropServicios':'Other services',
	'MenuDropFactura':'Bill your trip',
	'MenuDropImprima':'Print your boarding pass',
	'MenuItinerario':'Modify your itinerary',
	'PuntosIntercambio':'You not have the necesary points for complete the operation, of the #TotalPuntos# points you have, you can only use #PuntosRestantes# points, because #PuntosIntercambio# are profit points exchange',
    'ChbSeguros': 'Medical and legal assistance',
    'Aseguradora': 'Insurance carrier',
    'Seguro': 'insurance',
	'lblBsqHorario':'What time are you looking for?',
	'footerQSomos':'About us',
	'footerCertificado':'Certificates',
	'lblTpPasajeros':'Type of passengers',
	'lbPPiso':'First floor',
    'lbSPiso': 'Second floor',
    'btlDatos': 'Enter your data',
    'lblDatos': 'Complete your data',
    'btlCuenta': 'Login with your account',
    'lblCuenta': 'Enter with your data',
    'lblCorreoValido': 'Introduce a valid email',
    'lblCampoObliga': 'Obligatory field',
    'lblCamposObliga': 'Required fields',
    'lblContrase': 'Enter your password',
	'lbNMembresia':'Membership number',
    'btnEntrar': 'Enter',
    'btnEditarViaje': 'Edit my trip',
	'lbDetalleCompra': 'Detail of the purchase',
	'lbEligePago': 'Choose your payment method',
    'lbTarjeta': 'Bank cards',
    'lblMembresia': 'Membership',
    'lblSucursal': 'Branch and store',
	'lblPuntos': 'PAY WHIT POINTS',
	'lblOtros': 'OTHERS',
	'ComoyDondePagar':'how and where to pay?',
	'lbMejorCompra': 'You\'ve just made the best purchase!',
	'lbMonth': 'Month',
	'lbYear': 'Year',
	'lbPagoAME': 'Payment with American Express',
	'lbPagoVM': 'PAYMENT WITH VISA AND MASTERCARD',
	'lblTarjeta': 'Number card of Credit or Debit',
	'lbPagoCVV': 'CVV',
	'lblobligatorios': 'Required data',
	'lblNombresTH': 'Card holder first name',
	'lblApellidosTH': 'card holder last name',
	'lblCorreoTH': 'card holder email',
	'lbPais': 'Country',
	'lbPagoTR': 'Payment with Transfer',
	'lbPagoSantander': 'Payment with Santander points',
	'lbNombreTB': 'Name (as appeared on the card)',
	'lNumeroTB': 'Card number',
	'lbFechaTB': 'Expiration date',
	'lblCodigoTB': 'Security code',
	'lbPagoScotia': 'Payment with Scotia points',
	'lbRepiteToken': 'Repeat the token',
	'lbTokenTB': 'Token',
	'lbPagoViaja': 'Payment with points Viaja M&aacute;s',
	'lbPuntosRd': 'Points to Redeem',
	'lbRefCitiBanamex': 'Payment data referenced CitiBanamex',
	'lbRefoxxopay': 'Payment data referenced OXXO PAY',
	'lbReferencia': 'Reference',
	'lbVigencia': 'state of being in force',
	'lblVerPDF': 'See PDF',
	'lblSeguroI': 'Medical assistance one way',
	'lblSeguroR': 'Medical assistance back',
	'lbRedimirPt': 'redeem points',
	'lbVentaBoletos': 'Tickets sale',
    'titleMantteSesion': 'Session Maintenance',
    'lblIda': 'going',
    'lblRegreso': 'came back',
    'lblVerTodos': 'See All',
    'lblSeleccionaDestino': 'To',
    'lblSeleccionaFecha': 'Select a date for the ',
    'popuptitle': 'Protected Traveler',
    'popupcash': ', from your trip',
    'popupLuggage': 'You already have your luggage protected; ',
    'popupbag': 'your belongings and personal items, ',
    'popupdoctors': 'as well as your medical expenses in case of an accident or illness.',
    'popupNo': 'No, thanks',
    'popupSi': 'Yes, I accept insurance',
    'popupTerminos': 'Know all our terms and conditions of the Protected Traveler insurance',
    'clickpagos': 'CLICK HERE',
	'MenuPagoRef':'Referenced payments',
    'MenuViajeAh': 'Travel saving',
    'CerrarFiltro': 'CLOSE FILTERS',
    'PerzonalizarBusqueda': 'PERSONALIZE YOUR SEARCH',
    'MenuWALMART': 'WALMART',
    'MenuPAYNET': 'PAYNET',
    'MenuBANAMEX': 'BANAMEX',
    'disponibilidadPrecios': 'PRICE AVAILABILITY',
    'disponibilidad': 'Availability',
    'viajeroAnticipado': 'Advance Traveler',
	'MenuDropAgencia': 'Agencies',
	'popupcongrats': 'CONGRATULATIONS!',
	'popupdescripcionby': 'For only',
	'popupdescripcionsince': 'Even for ',
	'popupdays': '5 days',
	'lbPagoReferenciado': 'Payment data referenced'
};
// Mensajes de validaciones en alerts
var msjIN = {
	'ContrasenaNoPuedeQuedarVacia':'Enter the password',
	'ErroralConfirmarContrasena':'Error to confirm the password',
	'OperacionNoPuedeQuedarVacia':'The operation number cannot be empty.',
	'FavorTeclearUsuario':'Please enter a user',
	'FavorTeclearContrasena':'Please Enter the Password',
	'NoComprasdeMasde10Pasaj':'Not allowed a purchase over than 10 passengers',
	'NoPuedeViajarMenorSolo':'A child can not travel alone, an adult must accompany',
	'NecesitaSelecOrigen':'Please enter an origin',
	'NecesitaSelecDestino':'Please select a destination',
	'ErrorOrigDestIguales':'Error: origin a destination are the same',
	'ElegirFechaValida':'Please select a valid date',
	'FechaRegNoMenoraFechaSal':'The return date can not be lesser than the departure date',
	'DebeSelecTipoPasajeroalMenos':'Please select at least one type of passenger',
	'ElCampo':'The field ',  //verificar linea 1088 validaciones
	'NoDebeContenerNum':'must not contain numbers.',
	'DebeContenerSoloNum':'must contain only numbers',
	'NoTieneFormatoCorreo':' don´t have an email format.',  //verificar linea 1112 validaciones
	'Requerido':'Required',
	'IntroducSoloNumeros':'Introduce just numbers',
	'IntroducCorreoValido':'Introduce a valid email',
	'NecesarioAceptTermCond':'Is necesary to accept terms and conditions',
	'FaltaSeleccionar':'Need to select',
	'AsientosdeIda':'departure seat(s)',
	'AsientosdeRegreso':'Return seat(s)',
	'FaltaNombrePasajero':'Passenger name missing',
	'FaltaCaptNomPasajero':'Please capture the name of passenger',
	'RSFaltaApPaternoPasajero':'Passenger lastname missing',
	'RSFaltaCaptApPaternoPasajero':'Please capture the lastname of passenger',
	'FaltaCaptPasaporte':'Please capture the name of Visa',
	'FaltaCapturarDomic':'Please enter the address',
	'FaltaCapturarNumExt':'Please enter the address external number',
	'FaltaCapturarNumInt':'Please enter the address internal number',
	'FaltaCapturarDelMpio':'Please enter the Area or Municipality',
	'FaltaCapturarEstado':'Please enter the State',
	'FaltaCapturarCiudad':'Please enter a city',
	'ErrorenCodPos':'The field Zip Code must contain only numbers',
	'FaltaElegirPais':'Please choose a contry',
	'ErrorenTelef':'Please capture a valid phone number',
	'ErrorenEmail':'Please capture a valid email',
	'ParaContinuarAceptTermCond':'To continue you must agree the terms and conditions set in the price and travel in the lower part of the screen.',
	'DebeSelecTipoPasajero':'Please select a type of passenger',
	'FavorSelecCorrida':'Please select a trip',
	'CorridaRegNoPuedeSerSelec':' The return trip can\'t be select, because the departure date is lesser than the arrival date.',
	'NoPuedeSelecCorridaTraslapeconIda':'It´s not possible to select this trip because it´s overlapped whith the outward trip',
	'CantidadIncorrecta':'Incorrect amount please verify',
	'SoloAceptaNumeros':'Only accepts numbers',
	'PasajerosYaFueronSelec':'All passengers have already been selected',
	'TipoPagoInvalido':'This type of payment is invalid',
	'NoComprasdeMasde20Pasaj':'You can not make a pursache over 10 passengers',
	'MontoFichaNoPuedeSerCero':'The amount of the deposit order can´t be zero',
	'MontoFichaNoPuedeSerVacio':'The amount of the deposit order can´t be empty',
	'DepositoNoPuedeSerMayoraVenta':'The deposit order can´t be bigger than the purchase order',
	'FechaFinalNoMenoraInicial':'The final date can not be lesser than the initial date',
	'ElegirUsuarioparaContinuar':'Please choose a user to continue.',
	'Enero':'January',
	'Febrero':'February',
	'Marzo':'March',
	'Abril':'April',
	'Mayo':'May',
	'Junio':'Jun',
	'Julio':'July',
	'Agosto':'August',
	'Septiembre':'September',
	'Octubre':'October',
	'Noviembre':'November',
	'Diciembre':'December',
	'Lunes':'Mon',
	'Martes':'Tue',
	'Miercoles':'Wed',
	'Jueves':'Thu',
	'Viernes':'Fri',
	'Sabado':'Sat',
	'Domingo':'Sun',
	'informacionreq':'required Information',
	'mensajecap':'ERROR: You must solve the Captcha.',
	'RSNoPuedeSerMayorDe':'cannot be greater than',
	'RSNoPuedeSerMenorDe':'cannot be smallet than',
	'RSNoPuedeSerIgualA':'cannot be equal to',
	'Eliminarultimopasajero':'Unable to remove the last passenger',
	'MensajeLogin':'Successful access',
	'NitNoViacia':'The NIT number cannot be empty.',
	'IngreseDatos':'Enter the following data',
	'EsNecesarioLoguear':'You need to login to your account to Maxima Distincion to continue.',
	'NoEncontrado':' didnt match any item',
	'mensajecorreoduplicado':'The email of passengers must be different.',
	'usuariointercambio':'You can not enter because that do not match the passenger data to account.',
	'asientoSeleccion':'The seat: $, already been selected by another user&#33;',
	'asientoDisponible':'The seat: $, No available&#33;',
	'diagramaLongitud':'The seat: $, ist\'n exists&#33;',
	'SesionVtaReq':'You need to open a session to continue&#33;.',
	'NoRestPasajero':'It doesn\'t recognize the restriction $&#33;',
	'RestPasajeros':'The passenger type, $ is restricted to this sales channel&#33;.',
	'trnCorrIda':'You can\'t select trip and transfer&#33;',
	'trnCorrReg':'You can\'t select transfer and trip&#33;',
	'selTransCor':'Please select a option&#33;',
	'modificacionpasajeros':'It is necessary to accept the name change for the passenger 1',
	'selTipoSer':'You must select a Class of Service&#33;',
	'favorSelecServicio':'Please select a service type&#33;',
	'FechaInterFinal':'The date of exchange can\'t be less than the arrival date&#33;',
	'FechaInterSalida':'The date of exchange can\'t be less than the departure&#33;',
	'CorridaInterSalida':'I can\'t select this trip, because it overlaps with your departure&#33;',
	'CorridaInterLLegada':'I can\'t select this trip, because it overlaps with your arrival&#33;',
	'msjBoletoAbierto':'You can not select open tickets for $!',
	'contMinimoTel':'The Field must contain at least 10 digits!',
	'tooltipMenor':'From 3 to 11 years old',
	'tooltipInsen':'Valid discount presenting INAPAM credential',
	'tooltipPCD':'Different capacities',
	'tooltipPromocion':'Enter only if you have a promo code',
	'opercionNoVacio':'The operation number can\'t be left empty',
	'nitNoVacio':'The NIT can\'t remain empty',
    'tooltipCRM': 'You can login with the email you registered in Mi viaje or Viaja m&aacute;s',
    'Memdup': 'Membership duplicated.',
    'Meminco': 'Membership captured correctly.',
    'DatosMemInc': 'Capture membership data correctly.',
    'CapIDCRM': 'Capture the Member ID.',
    'CapEmailCRM': 'Capture the email',
    'CapPassCRM': 'Capture the password.',
    'tooltipSeguros': 'Acquire your insurance to protect you from any unexpected situation during your trip for $ (taxes included).',
    'tooltipSeguroslink': 'More information here.',
	'CapTarjeta': 'Missing capture card number.',
	'CapCardVV': 'Missing capture security number.',
	'CapFechaExp.': 'It\'s necessary to capture the expiration month.',
	'MesExpInvalido': 'Invalid expiration month.',
	'YearExpInvalido': 'It\'s necessary to capture the expiration year.',
	'CapNombreTH': 'Missing capture cardholder name.',
	'CapApellidoTH': 'Missing capture cardholder\'s last name.',
	'CapCorreoTH': 'The cardholder\'s email must be captured.',
	'CorreoTHInvalido': 'Cardholder email is incorrect.'
};
// Dias de laSemana
var DiasSemanaIN = new Array("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday");
function RecuperaTxtIN()
{
	return txtIN;
}
function RecuperaMsjIN()
{
	return msjIN;
}
function RecupColumnasIN()
{
	return ColumnasIN;
}
function RecupPaisesIN()
{
	return paisesIN;
}
function RecupEstadoIN()
{
	return estadoIN;
}
function RecupDiasSemanaIN() {
    return DiasSemanaIN;
}
function DataTableIN()
{
	return DataT_IN;
}
var DataT_IN = {
		"sEmptyTable":     "No data available in table",
		"sInfo":           "_START_ to _END_ of _TOTAL_ trips results",
		"sInfoEmpty":      "Showing 0 to 0 of 0 trips results",
		"sInfoFiltered":   "(Filtered from _MAX_ total trips results)",
		"sInfoPostFix":    "",
		"sInfoThousands":  ",",
		"sLengthMenu":     "Show _MENU_ entries",
		"sLoadingRecords": "Loading...",
		"sProcessing":     "Processing...",
		"sSearch":         "Search:",
		"sZeroRecords":    "No matching trips found",
		"oPaginate": {
			"sFirst":    "First",
			"sLast":     "Last",
			"sNext":     "Next",
			"sPrevious": "Previous"
		},
		"oAria": {
			"sSortAscending":  ": Activate to sort column asc",
			"sSortDescending": ": Activate to sort column dsc"
		}
	};