//Idioma Español - Textos y Mensajes
var ColumnasES = eval( [
	{"id": "tramoTrans", "nombreColumna": "Tramo transbordo", "width": "9%"},
	{"id": "horaSalida", "nombreColumna": "Salida", "width": "9%"},
	{"id": "fechaSalida", "nombreColumna": "Fecha salida", "width": "9%"},
	{"id": "horaLlegada", "nombreColumna": "Llegada", "width": "10%"},
	{"id": "fechaLlegada", "nombreColumna": "Fecha llegada", "width": "8%"},
	{"id": "itinerario", "nombreColumna": "Escalas", "width": "10%"},
	{"id": "descuentos", "nombreColumna": "Descuentos disponibles", "width": "8%"},
	{"id": "claseDeServicio", "nombreColumna": "Servicio", "width": "15%"},	
	{"id": "pisos", "nombreColumna": "Autob&uacute;s", "width": "13%"},
	{"id": "linea", "nombreColumna": "Marca", "width": "13%"},			
	{"id": "transbordo", "nombreColumna": "Transbordos", "width": "8%"},
	{"id": "tarifa", "nombreColumna": "Precio", "width": "12%"},
	{"id": "enl_tar", "nombreColumna": "Precio", "width": "12%"},
    { "id": "promocion", "nombreColumna": "Viajero Anticipado", "width": "8%"},
	{"id": "enl_prom", "nombreColumna": "Promoci&oacute;n", "width": "8%"},
	{"id": "selecciona", "nombreColumna": "Elegir", "width": "13%"},
	{"id": "enl_sel", "nombreColumna": "Seleccionar", "width": "13%"},
	{"id": "secciones", "nombreColumna": "Secciones", "width": "13%"}
]);
// Textos "duros" en el codigo HTML
var txtES = {
	'lblSalioMal':'Algo sali&oacute; mal, por favor vuelve a intentarlo',
	'lblGuardarCambios':'Guardar Cambios',
	'PASO':'PASO',
	'DE':'DE',
	'MSG_codigopromo':'Se cargaran de nuevo la pagina',
	'ADisponible':'Asiento Disponible',
	'AOcupado':'Asiento Ocupado',
	'ASeleccionado':'Asiento Seleccionado',
	'SALIDA':'Origen',
	'REGRESO':'Destino',
	'REGISTRO':'Registro',
	'ASIENTOS':'Asientos',
	'RESUMEN':'Resumen',
	'PAGO':'Pago',
	'CONFIRMACION':'Confirmaci&oacute;n',
	'fechaSalida':'Fecha de salida',
	'horaSalida':'Hora de salida',
	'fechaLlegada':'Fecha de llegada',
	'horaLlegada':'Hora de llegada',
	'fechaRegreso':'Fecha de regreso',
	'Horario':'Horario',
	'Servicio':'Servicio',
	'Linea':'Linea',
	'Costo':'Costo',
	'Itinerario':'Itinerario',
	'Selecciona':'Seleccionar',
	'NoHaySalidasParaCriterio':'No hay disponibilidad para esta solicitud, int&eacute;ntelo nuevamente con otra fecha o tipo de pasajero...',
	'VerCostos':'ver costos',
	'EstaIntercambiandoNumOper':'Est&aacute;s intercambiando n&uacute;mero(s) de operaci&oacute;n',
	'CostoTotal':'Costo total',
	'CamposRequeridos':'Requiere texto',
	'FormadePago':'Forma de Pago',
	'Efectivo':'Efectivo',
	'PagoconTarjeta':'Pago con Tarjeta',
	'Domicilio':'Domicilio',
	'Ciudad':'Ciudad',
	'CodPostal':'C&oacute;digo postal',
	'RSCalle':'Direcci&oacute;n',
	'RSNumExt':'N&uacute;m. Exterior',
	'RSNumInt':'N&uacute;m. Interior',
	'RSDelMpio':'Delegaci&oacute;n / Municipio',
	'RSEstado':'Estado',
	'RSNombre':'nombre',
	'RSApPaterno':'apellido paterno',
	'RSApMaterno':'apellido materno',
	'RSNombreD':'nombre',
	'RSApPaternoD':'apellido paterno',
	'RSApMaternoD':'apellido materno',
	'RSApPaternoA':'apellido paterno',
	'RSApMaternoA':'apellido materno',
	//'RSSeparador':'»',
	'RSSeparador':String.fromCharCode(187),
	//'RSSeparador2':'|',
	'RSSeparador2':String.fromCharCode(124),
	'Pais':'Pais',
	'Estado':'Estado',
	'TelCasaOfic':'Tel&eacute;fono (casa/oficina)',
	'CorreoElectronico':'correo electr&oacute;nico',
	'IncluyaLada':'incluya la clave de larga distancia',
	'VerTermCondic':'Leer t&eacute;rminos, condiciones',
	'FechadeRegreso':'Fecha de regreso',
	'RegistrodePasajeros':'Registro de pasajeros',
	'Utiliza1erNomParaPasajeros':'Utilizar el primer nombre para todos los pasajeros',
	'Adulto':'Adulto',
	'Menor':'Menor',
	'Insen':'INAPAM',
	'Estudiante':'Estudiante',
	'Profesor':'Profesor',
	'Maestro':'Maestro',
	'PCD':'PCD',
	'VerItinerario':'Ver',
	'OcultarItinerario':'Ocultar',
	'AceptoTerminosCond':'Acepto',
	'Y':'y',
	'CaptureTxtComoEnImg':'Capture el texto como se muestra en la imagen',
	'RefrescarImagen':'Refrescar imagen',
	'Dia':'D&iacute;a',
	'Hora':'Hora',
	'Origen':'Origen',
	'selectNoResultados':'No se encontraron resultados',
	'Destino':'Destino',
	'OrigenMayus':'Origen',
	'DestinoMayus':'Destino',
	'DatosDelPasajero':'Datos del pasajero',
	'DatosDel':'Datos del ',
	'Pasajero':'Pasajero',
	'Asiento':'Asiento',
	'AsientoMayus':'Asiento',
	'ViajedeRegreso':'Viaje de regreso',
	'ViajedeSalida':'Viaje de ida', 
	'SelecAsientoSalidaSigPasaj':'Seleccione el asiento de salida para el siguiente pasajero:',
	'SelecAsientoRegresoSigPasaj':'Seleccione el asiento de regreso para el siguiente pasajero:',
	'AsientoOcupado':'Asiento ocupado',
	'AsientoDisponible':'Asiento dispobible',
	'AsientoSeleccionado':'Asiento seleccionado',
	'Aviso':'Aviso',
	'PagoCanceladoB':'Pago cancelado por el usuario',
	'SeleccionaOtraFormaPago':'Selecciona otra forma de pago',
	'ViajeSencillo':'Sencillo',
	'ViajeRedondo':'Redondo',
	'ViajeAbierto':'Abierto',
	'ClasedeServicio':'Clase de servicio',
	'NumOperacion':'N&uacute;mero de operaci&oacute;n',
	'NIT':'NIT',
	'ContrasenaActual':'Contrase&ntilde;a actual',
	'ContrasenaNueva':'Contrase&ntilde;a nueva',
	'ConfirmarContrasena':'Confirma contrase&ntilde;a',
	'FechaInicial':'Fecha inicial',
	'FechaFinal':'Fecha final',
	'SaldoaDepositar':'Saldo a depositar',
	'MontoenFicha':'Monto en ficha',
	'PresContinuarParaEmitirFicha':'Presione &quot;Continuar&quot; para emitir la ficha de dep&oacute;sito',
	'FichadeDeposito':'Ficha de dep&oacute;sito',
	'AgenciaMayus':'Agencia',
	'Banco':'Banco',
	'Sucursal':'Sucursal',
	'Cuenta':'Cuenta',
	'NumReferInterbanc':'N&uacute;mero de ref. Interbancaria',
	'CantidadaDepositar':'Cantidad a depositar',
	'DatosdeCompra':'Datos de compra',
	'TiempoRestante':'Tiempo restante',
	'ParaCompletarPaso':'Para completar este paso',
	'SuSesionExpirara':'Su sesi&oacute;n expira: &#191;Deseas agregar mas tiempo?',
	'Ahorro':'Ahorro',
	'Promocion':'Promoci&oacute;n',
	'Pasajeros':'Pasajeros',
	'GraciasporSuCompra':'Gracias por su compra',
	'VentaBoletosAgencias':'Venta de boletos para agencias',
	'Agencia':'Agencia',
	'Usuario':'Usuario',
	'Administrador':'Administrador',
	'Venta':'Venta',
	'BoletoAbierto':'Boleto Abierto',
	'Intercambio':'Intercambio',
	'Cancelacion':'Cancelaci&oacute;n',
	'CambiarContrasena':'Cambiar contrase&ntilde;a',
	'Saldos':'Saldos',
	'Movimientos':'Movimientos',
	'CerrarSesion':'Cerrar Sesi&oacute;n',
	'AdministradorAgencias':'Administrador Agencias',
	'Nombre':'Nombre',
	'Elegir':'Elegir',
	'DiaMayus':'D&iacute;a',
	'Inicio':'Inicio',
	'Fin':'Fin',
	'DiaActivo':'D&iacute;a activo',
	'NumTransacEmpresa':'No. Transaccion de la empresa',
	'NumAutorizBanco':'No. Autorizaci&oacute;n del Banco',
	'NumReciboBanco':'No. Recibo del Banco',
	'RSPagadoEnBanco':'Pagado en el Banco',
	'RSSaldoConsumidoConvenio':'Saldo Consumido del Convenio',
	'RSSaldoConsumidoVF':'Saldo Consumido del Programa de Lealtad',
	'Operacion':'Operaci&oacute;n',
	'Tipo':'Tipo',
	'Monto':'Monto',
	'Descuento':'Descuento',
	'ParaImpreBoletosenTaquilla':'Para la impresi&oacute;n de sus boletos en taquilla, deber&aacute; presentar copia de identificaci&oacute;n oficial vigente',
	'PasajeroResumen':'Datos del pasajero',
	'textorequiere':'campos requeridos',
	'pasaporte':'VISA',
	'totalMay':'Total',
	'formapago1':'Tarjeta mexicana',
	'formapago2':'Tarjeta americana',
	'botonfiltro':'Buscar',
	'tipoviaje1':'Viaje Sencillo',
	'tipoviaje2':'Viaje Redondo',
	'titulofiltros':'Agenda tu viaje',
	'origenfil':'Origen',
	'destinofil':'Destino',
	'fechasalidafil':'Salida',
	'fecharegresofil':'Regreso',
	'cargandoorides':'Cargando...',
	'telef':'Telefono',
	'correop':'Correo',
	'Nombrepas':'Nombre',
	'RSInfoAdicional':'Informacion adicional',
	'RSPromocion':'C&oacute;digo de promoci&oacute;n',
	'RSCorreo':'Correo Electr&oacute;nico',
	'RSTarjetaBancaria':'Tarjeta Bancaria',
	'RSPuntosViajeroFrecuente':'Puntos de Viajero Frecuente',
	'RSConvenio':'Convenio',
	'RSNumeroConvenio':'N&uacute;mero de Convenio',
	'RSARedimir':'A Redimir',
	'RSPuntos':'Puntos',
	'RSAPagarBanco':'A Pagar En El Banco',
	'RSAPagar':'A Pagar',
	'RSNumero':'N&uacute;mero',
	'RSPromocionInvalida':'Promoci&oacute;n inv&aacute;lida o no existe',
	'RSConvenioInvalido':'Convenio inv&aacute;lido o no existe',
	'RSNIP':'Nip',
	'RSNIPInvalido':'Nip inv&aacute;lido o el miembro no existe',
	'Totalres':'Total',
	'MontoIva':'IVA',
	'Montobruto':'Precio',
	'TipoPasRes':'T. pasajero',
	'Veravisopriva':'Aviso de privacidad',
	'SeparadorTermyPriva':'y',
	'mensajebancoerrA':'No cierre el navegador, su transacci&oacute;n est&aacute; siendo procesada.',
	'mensajebancoerrB':'Si ocurre un error favor de llamar al:',
	'mensajebancoerrC':'Su n&uacute;mero de sesi&oacute;n es:',
	'mensajebancoerrD':'Su tarjeta fue:',
	'Costo_n':'Precio normal',
	'sencillo':'Un piso',
	'doble':'Doble piso',
	'LeyendaVFCRM_1': 'Nombre Viajero Frecuente',
	'LeyendaVFCRM_2': 'Nivel de Membres&iacute;a',
	'LeyendaVFCRM_3': 'Puntos Disponibles',
	'TituloVenta': 'Venta en l&iacute;nea',
	'SubtituloVentaCorridas': 'Consulte horarios',
	'SubtituloPersonaliza': 'Completa tus datos',
	'SubtituloAsientos': 'Seleccione su asiento',
	'SubtituloResumen': 'Confirmaci&oacute;n y pago',
	'SubtituloPago': 'Realice su Pago',
	'SubtituloDetalle': 'Confirme su viaje',
	'MenuFiltro1': 'Autob&uacute;s',
	'MenuFiltro2': '+ Hotel',
	'MenuFiltro3': 'Consulta horarios',
	'tipoviajetitulo': 'Tipo de viaje',
	'BotonMaximaF': 'Ingresar a m&aacute;xima distinci&oacute;n',
	'BotonAgenciaF': 'Ingresar como agencia',
	'BotonContinuar': 'Continuar',
	'BotonRegresar': 'Regresar',
	'BotonConsultar': 'Consultar',
	'VFContrasena': 'Contrase&ntilde;a',
	'FiltroCorridasTipoViajeI1': 'Viaje de',
	'FiltroCorridasTipoViajeR1': 'Viaje de',
	'FiltroCorridasTipoViajeI2': 'Ida',
	'FiltroCorridasTipoViajeR2': 'Regreso',
	'FiltroCorridasViaje': 'Viaje',
	'VFLoginnombre': 'Bienvenido',
	'VFLoginpuntos': 'Puntos',
	'CorridasDe': 'De',
	'CorridasA': 'a',
	'CorridasFecha': 'Fecha',
	'ItinerarioTit': 'Escalas',
	'ItinerarioOD': 'Tramo',
	'ItinerarioFS': 'Fecha salida',
	'ItinerarioHS': 'Hora salida',
	'ItinerarioFL': 'Fecha llegada',
	'ItinerarioHL': 'Hora llegada',
	'ItinerarioCerrar': 'Cerrar',
	'CorridasBotondes': 'Ver',
	'CorridasDescuentos': 'Descuentos disponibles',
	'LVPertenesco': 'Pertenezco a',
    'LVMiembro': 'ID miembro o correo electr\u00F3nico',
	'LVIngresar': 'Ingresar',
	'MVIngresar': 'Ingresar con',
	'MVIngresar2': 'Mi viaje',
	'PersonalizaVer': 'Ver',
    'PersonalizaTerminos': 't&eacute;rminos y condiciones',
	'PersonalizaPoliticas': 'Aviso de privacidad',
	'AsientosAgregar': 'Agregar pasajero',
	'ResumenMarca': 'Marca',
	'ResumenAutobus': 'Autob&uacute;s',
	'ResumenTPas': 'Tipo de pasajero',
	'ResumenFP': 'Seleccione su tipo de pago',
	'ResumenTotal': 'Importe total a pagar',
	'ResumenAhorro': 'Usted ahorr&oacute;',
	'ResumenIntCantNIP': ', Si desea pagar con puntos, introduzca su Nip y la cantidad de puntos que usar&aacute; en esta transacci&oacute;n.',
	'ResumenPagar': 'Pagar',
	'ResumenCuentaPtos': 'Usted cuenta con',
	'ResumenPtos': 'Puntos',
	'DetalleGuardar': 'Guardar pase',
	'DetalleImprimir': 'Imprimir',
	'Amextitulo': 'Introduce la informaci&oacute;n requerida tal como aparece en tu documentaci&oacute;n.',
	'AmexMonto': 'Monto a Pagar',
	'AmexTarjeta': 'N&uacute;mero de la Tarjeta de Cr&eacute;dito / D&eacute;bito',
	'AmexSeguridad': 'CVV',
	'Amexfv': 'Fecha Vencimiento. Mes/A&ntilde;o',
	'AmexNombre': 'Nombre(s) del tarjetahabiente',
	'AmexApellido': 'Apellido del tarjetahabiente',
	'AmexDireccion': 'Direccion del tarjetahabiente',
	'AmexTel': 'Tel&eacute;fono del tarjetahabiente',
	'AmexCorreo': 'Correo del tarjetahabiente',
	'MenuSuperiorDes': 'Destinos',
	'MenuSuperiorBol': 'Boletos autob&uacute;s',
	'MenuSuperiorProm': 'Promociones',
	'MenuSuperiorBen': 'Disfruta ETN Turistar',
	'MenuSuperiorHor': 'Horarios',
	'IntercambioOpePub': 'N&uacute;mero(s) de operaci&oacute;n',
	'NombrePasI': 'Nombre pasajero',
	'OrigenI': 'Origen',
	'DestinoI': 'Destino',
	'CorreoI': 'Correo',
	'CostoI': 'Costo',
	'ViajeIda': 'Fecha de ida',
	'ResumenBoletoAbierto': 'Resumen de Compra y Forma de Pago',
	'paseAbordaje': 'Emisi&oacute;n de Boleto Abierto',
	'EsperaVIP': 'Espera VIP',
	'ServicioABordo': 'Servicios a Bordo',
	'SCharters': 'Salidas Charters',
	'DatosViaje': 'Datos de viaje',
	'UseAbierto': 'Utiliza tu Boleto Abierto',
	'ModIti': 'MODIFICA TU ITINERARIO',
	'CapturaCodigo': 'Por favor introduzca el c&oacute;digo que se muestra a continuaci&oacute;n.',
	'BotonHorariosCom': 'Comprar',
	'AdvertenciaIntercambio': 'En las modificaciones de itinerario con un destino que sea de un costo menor no habr&aacute; reembolso ni devoluci&oacute;n',
	'TransCel': 'Ingresa tu C&oacute;digo Transfer',
	'chatenlinea': 'en l&iacute;nea',
	'atencionaclientes': 'Atenci&oacute;n a clientes',
	'NotaEscalasPopUp': 'Nota: La lista muestra horarios y fechas locales',
	'Refacturar': 'Esta operacion a intercambiar ya fue facturada, se cancelara su factura, requiere se  facture su nueva operacion?',
	'ntGuardaPase': 'El n&uacute;mero de operaci&oacute;n y NIT de su pase de abordar se han enviado a su correo electr&oacute;nico',
	'ntGuardaPase2': 'Usted tambi&eacute;n puede guardar en su dispositivo su pase de abordar oprimiendo el bot&oacute;n "Guardar Pase" ubicado en la parte inferior de esta pantalla.',
	'ConfirmAbreSesion': '&#191;Confirma que desea abrir la sesi&oacute;n?',
	'CerrarSesionVta': 'Terminar sesi&oacute;n',
	'AbrirSesionVta': 'Abrir sesi&oacute;n',
	'ConfirmCierraSesion': '&#191;Confirma que desea cerrar la sesi&oacute;n?',
	'CuadreCaja': 'Se realizar&aacute; el cuadre de caja&#33;&#33;',
    'detalleAhorro': 'T&uacute; ahorraste',
	'otraDiscapacidad': 'PCD',
	'AdultoPlu': 'Adultos',
	'MenorPlu': 'Menores',
	'MaestroPlu': 'Maestros',
	'EstudiantePlu': 'Estudiantes',
	'TipoFormaPagoMixto': 'Este intercambio solo se puede pagar con',
	'EfectivoM': 'Efectivo',
	'TarjetaM': 'Tarjeta',
	'PuntosM': 'Puntos',
	'TransferM': 'Transfer',
	'RecargaCapcha': 'Recarga $ Imagen',
	'DatoDetalle': 'Ver Detalle',
	'TipoBol': 'Tipo de boleto',
	'datoEnlace': 'Con transbordo',
	'datoEnlace1': 'Con Transbordo y Viaje directo',
	'datoEnlace2': 'Viaje directo y Con Transbordo',
	'datoTramo': 'Tramo',
	'btnEnlace': 'Elegir este viaje de ',
	'btnSelAsiento': 'Selecciona tu asiento',
	'chViajaDirecto': 'Viaja directo',
	'btnDelDiag': 'Eliminar',
	'titleViajesEnl': 'Viajes',
	'titleViajesTrn': 'Viajes con Enlaces',
	'QueEsPaypal': '&iquest;Qu&eacute; es PayPal?',
	'PaypalDes1': 'Es un medio de pago f&aacute;cil, r&aacute;pido y seguro.',
	'PaypalDes2': 'Puede hacer pagos con tarjeta de cr&eacute;dito y d&eacute;bito.',
	'PaypalDes3': 'Registre en PayPal sus datos financieros una sola vez. No necesitar&aacute; proporcionarlos en compras posteriores.',
	'PaypalDes4': 'M&aacute;s de 100 millones de personas en el mundo utilizan PayPal.',
	'PaypalDes5': 'PayPal protege su informaci&uacute;n: No compartimos sus datos financieros.',
	'ComoPagarCon': '&#191;Como pagar con',
	'Envia': 'Env&iacute;a',
	'Confirma': 'Confirma',
	'Recibiras': 'Recibir&aacute;s',
	'Ingresa': 'Ingresa',
	'TransfDes1': 'mensaje de texto al 4040 con la palabra C&oacute;digo (espacio) Monto. Ejemplo. C&oacute;digo 300 o a trav&eacute;s de la APP Transfer.',
	'TransfDes2': 'tu solicitud del C&oacute;digo Transfer ingresando tu NIP.',
	'TransfDes3': 'un C&oacute;digo Transfer Banamex.',
	'TransfDes4': 'tu C&oacute;digo Transfer y finaliza la compra de tus boletos de autob&uacute;s.',
	'VerifiqueDatos': 'Verifique sus Datos',
	'VerifiqueDatosAb': 'Verifique sus Datos boleto Abierto',
	'PaseAbordar': 'Su pase de abordar',
	'FiltrosAgen': 'Filtros Agencias',
	'FiltroAgenAb': 'Filtro Agencias Abierto',
	'RegistroBolA': 'Registro de datos boleto abierto',
	'DatosIntercambio': 'Datos Intercambio',
	'AdminAgencias': 'Administrador Agencias',
	'EligeHoSal': 'Elige el horario de salida',
	'EligeHorIR': 'Elige el horario de ida y regreso',
	'EligeHorReg': 'Elige el horario de regreso',
	'RegistroDatos': 'Registro de datos',
	'EligeAsiento': 'Elige el Asiento',
	'EligeAsIR': 'Elige el Asiento de ida y regreso',
	'EligeAsRe': 'Elige el Asiento Regreso',
	'titleCorSel': 'Selecciona tu horario',
	'taquillas': 'Taquillas',
	'titlewindow': 'Informaci&oacute;n requerida',
	'cantMaximaAdulto': 'La cantidad m&aacute;xima de pasajero ADULTO es 10',
	'cantMaximaMenor': 'La cantidad m&aacute;xima de pasajero MENOR es 3',
	'cantMaximaInsen': 'La cantidad m&aacute;xima de pasajero INAPAM es 3',
	'cantMaximaEst': 'La cantidad m&aacute;xima de pasajero ESTUDIANTE es 3',
	'cantMaximaProf': 'La cantidad m&aacute;xima de pasajero PROFESOR es 2',
	'cantMaximaPCD': 'La cantidad m&aacute;xima de pasajero PCD es 1',
	'HorarioViaje': 'Horario de Viaje',
	'titleEnlace': 'Enlaces',
	'boxTitleUser': 'Personaliza tu b&uacute;squeda',
	'textHViaje': 'Todos, Ma&ntilde;ana, Tarde, Noche',
	'textEServicio': 'Todos, Local, De Paso',
	'textCEscalas': 'Todas, Con Escalas, Sin Escalas',
	'textTEnlaces': 'Todos, Con Enlaces, Sin Enlaces',
	'textTAutobus': 'Ambos, Un piso, Doble piso',
	'textCEmpresa': 'Ambas, ETN, Turistar',
	'btnEditDiag': 'Editar',
	'btnAcepDiag': 'Aceptar',
	'PrecioDatos': 'Precio con descuento',
	'selSerMovil': 'Selecciona Servicio',
	'titleCRMMD': 'M&aacute;xima distinci&oacute;n',
	'titleCRMVM': 'Viaja m&aacute;s',
    'btnIniciaSesion': 'Iniciar Sesi&#243n en Viaja M&aacute;s',
	'titleCompraAqui': 'Compra Aqu&iacute; tus boletos de autob&uacute;s',
	'RSEscriba': 'Escribe tu',
	'subtitleAg': 'Adquirir Boleto de Autob&uacute;s',
	'titleLoginAgencia': 'Ingresa tus datos y compra tus boletos de autob&uacute;s',
	'btnCompartirViaje': 'Compartir mi viaje en Facebook',
	'txtCompartirViaje': 'Click si desea compartir con sus contactos que viajas por ETN Turistar Lujo',
	'lblCompartirViaje': 'Compartir mi viaje',
	'IngreseDatos': 'Ingresa los siguientes datos',
	'lblMercadoPago': 'ID transaccion MercadoPago',
	'lblPaypalPago': 'ID transaccion Paypal',
	'lblEmailPaypalPago': 'Email Paypal de Cliente',
	'lblUsuariosAgencia': 'Usuarios Agencia',
	'lblIntercambioBoleto': 'Intercambio de Boletos',
	'lblCancelBoleto': 'Cancelaci&oacute;n de Boletos',
	'lblCambiarContra': 'Cambiar Contrase&ntilde;a',
	'lblReportMovimientos': 'Reporte de Movimientos',
	'lblSaldosAgencia': 'Saldos agencias',
	'lblSaldoDeposito': 'Saldo a depositar',
	'lblMontoFicha': 'Monto en ficha',
	'lblFichaDeposito': 'Ficha de dep&oacute;sito agencia',
	'BotonEnviar': 'Enviar',
	'lblSesionesUsiario': 'Sesiones del usuario',
	'lblHeaderSesion': 'No. Sesi&oacute;n',
	'lblHeaderFApertura': 'Fecha Apertura',
	'lblHeaderHApertura': 'Hora Apertura',
	'lblHeaderFCierre': 'Fecha Cierre',
	'lblHeaderHCierre': 'Hora Cierre',
	'lblHeaderCuadreCaja': 'Cuadre Caja',
	'lblCapturaCuadreCaja': 'Captura Manual de Cuadre de Caja',
	'lblHeaderConcepto': 'Concepto',
	'lblHeaderValor': 'Valor',
	'MenuAutobus': 'Autobuses',
	'MenuTipoAutobus': 'Tipos de Autob&uacute;s',
	'MenuServabordo': 'Servicios a bordo',
	'MenuTerminales': 'Terminales',
	'MenuSalaEspera': 'Salas de Espera',
	'MenuBoletos': 'Boletos de autob&uacute;s',
	'MenuTiposBoleto': 'Tipos de Boleto',
	'MenuPuntosVenta': 'Taquillas y Puntos de venta',
	'MenuAgenciasAfil': 'Agencias Afilidas',
	'MenuCentroContacto': 'Centro de Contacto',
	'MenuOxxo': 'Oxxo',
	'MenuPriceTravel': 'Price Travel',
	'MenuBeneficios': 'Beneficios Costaline',
	'MenuAcerca': 'Acerca de nosotros',
	'MenuContacto': 'Contacto',
	'MenuPreguntas': 'Preguntas frecuentes',
	'MenuBolsatrabajo': 'Bolsa de trabajo',
	'MenuDondeComprar': '&#191;D&oacute;nde comprar?',
	'MenuPaqueteria': 'Paqueter&iacute;a',
	'MenuRentaBus': 'Renta de autobuses',
	'MenuBusHotel': 'Autob&uacutes + Hotel',
	'MenuDropServicios': 'Otros Servicios',
	'MenuDropFactura': 'Factura tu viaje',
	'MenuDropImprima': 'Imprime tu pase de abordar',
	'MenuItinerario': 'Modifica tu itinerario',
    'PuntosIntercambio': 'No cuentas con los puntos necesarios para completar esta operaci&#243n, de los #TotalPuntos# puntos, solo puedes utilizar #PuntosRestantes# puntos, porque #PuntosIntercambio# son puntos beneficio del intercambio.',
    'ChbSeguros': 'Asistencia m&eacute;dica y legal',
    'Aseguradora': 'Aseguradora',
    'Seguro': 'Seguro',
	'lblBsqHorario': '&#191;Qu&eacute; horario buscas?',
	'footerQSomos': '&#191;Quienes somos?',
	'footerCertificado': 'Certificados',
	'lblTpPasajeros': 'Tipos de pasajeros',
	'lbPPiso': 'Primer Piso',
    'lbSPiso': 'Segundo Piso',
    'btlDatos': 'Ingresa tus datos',
    'lblDatos': 'Completa tus datos',
    'btlCuenta': 'Ingresa con tu cuenta',
    'lblCuenta': 'Ingresa como viajero frecuente',
    'lblCorreoValido': 'Ingresa correo v&aacute;lido',
    'lblCampoObliga': 'Campo obligatorio',
    'lblCamposObliga': 'Campos obligatorios',
    'lblContrase': 'Ingresa tu contrase&#241;a',
	'lbNMembresia': 'N&uacute;mero Membres&iacute;a',
    'btnEntrar': 'Entrar',
    'btnEditarViaje': 'Editar mi viaje',
	'lbDetalleCompra': 'Detalle de la compra',
	'lbEligePago': 'Elige tu forma de pago',
    'lbTarjeta': 'Tarjetas bancarias',
    'lblMembresia': 'Membres&iacute;a',
	'lblSucursal': 'Sucursal y tienda',
	'lblPuntos': 'PAGO CON PUNTOS',
	'lblOtros': 'OTROS',
	'ComoyDondePagar':'&iquest;C&oacute;mo Pagar?',
	'lbMejorCompra': '&iexcl;Acabas de hacer la mejor compra!',
	'lbMonth': 'Mes',
	'lbYear': 'A&ntilde;o',
	'lbPagoAME': 'Pago con American Express',
	'lbPagoVM': 'PAGO CON VISA Y MASTERCARD',
	'lblTarjeta': 'N&uacute;mero de la Tarjeta de Cr&eacute;dito o D&eacute;bito',
	'lbPagoCVV': 'CVV',
	'lblNombresTH': 'Nombre del Tarjetahabiente',
	'lblobligatorios': 'Datos obligatorios',
	'lblApellidosTH': 'Apellidos del Tarjetahabiente',
	'lblCorreoTH': 'Correo del Tarjetahabiente',
	'lbPais': 'Pa&iacute;s',
	'lbPagoTR': 'Pago con Transfer',
	'lbPagoSantander': 'Pago con puntos Santander',
	'lbNombreTB': 'Nombre (como aparece en la tarjeta)',
	'lNumeroTB': 'N&uacute;mero de Tarjeta',
	'lbFechaTB': 'Fecha de vencimiento',
	'lblCodigoTB': 'C&oacute;digo de Seguridad',
	'lbPagoScotia': 'Pago con puntos Scotia',
	'lbRepiteToken': 'Repetir el token',
	'lbTokenTB': 'Token',
	'lbPagoViaja': 'Pago con puntos Viaja M&aacute;s',
	'lbPuntosRd': 'Puntos a Redimir',
	'lbRefCitiBanamex': 'Datos de pago referenciado CitiBanamex',
	'lbRefoxxopay': 'Datos de pago OXXO PAY',
	'lbReferencia': 'Referencia',
	'lbVigencia': 'Vigencia',
	'lblVerPDF': 'Ver PDF',
    'lblSeguroI': 'Asistencia m\u00E9dica ida',
    'lblSeguroR': 'Asistencia m\u00E9dica regreso',
	'lbRedimirPt': 'redimir puntos',
	'lbVentaBoletos': 'Venta de boletos',
    'titleMantteSesion': 'Mantenimiento de sesiones',
    'lblIda': 'ida',
    'lblRegreso': 'regreso',
    'lblVerTodos': 'Ver Todos',
    'lblSeleccionaDestino': 'Seleccione un destino',
    'lblSeleccionaFecha': 'Seleccionar una fecha para el ',
    'popuptitle': 'Viajero Protegido',
    'popupcash': ', a partir de tu viaje.',
    'popupLuggage': 'ya tienes protegido tu equipaje; ',
    'popupbag': 'tus pertenencias y art&iacute;culos personales, ',
    'popupdoctors': 'as&iacute; como tus gastos m&eacute;dicos en caso de un accidente o enfermedad.',
    'popupNo': 'No, gracias',
    'popupSi': 'S\u00ED, acepto seguro',
    'popupTerminos': 'Conoce todos nuestros t\u00E9rminos y condiciones del seguro Viajero Protegido',
    'clickpagos':'DA CLICK AQU\u00CD',
	'MenuPagoRef':'Pagos referenciados',
    'MenuViajeAh': 'Viaja ahorrando',
    'CerrarFiltro': 'CERRAR FILTROS',
    'PerzonalizarBusqueda': 'PERSONALIZA TU B\u00DASQUEDA',
    'MenuWALMART': 'WALMART',
    'MenuPAYNET': 'PAYNET',
    'MenuBANAMEX': 'BANAMEX',
    'disponibilidadPrecios': 'DISPONIBILIDAD DE PRECIOS',
    'disponibilidad': 'Disponibilidad',
    'viajeroAnticipado': 'Viajero Anticipado',
	'MenuDropAgencia': 'Agencias',
	'popupcongrats': '&iexcl;FELICIDADES!',
	'popupdescripcionby': 'Por s&oacute;lo ',
	'popupdescripcionsince': 'Hasta por ',
	'popupdays': '5 d&iacute;as',
	'lbPagoReferenciado': 'Datos pago referenciado'
};
// Mensajes de validaciones en alerts
var msjES = {
	'ContrasenaNoPuedeQuedarVacia':'La contrase&ntilde;a no puede quedar vacia',
	'ErroralConfirmarContrasena':'Error al confirmar contrase&ntilde;a',
	'OperacionNoPuedeQuedarVacia':'La Operacion no debe quedar vac&iacute;a.',
	'FavorTeclearUsuario':'Favor de Teclear el Usuario',
	'FavorTeclearContrasena':'Favor de Teclear la Contrase&ntilde;a',
	'NoComprasdeMasde10Pasaj':'No se puede hacer una compra de mas de 10 pasajeros',
	'NoPuedeViajarMenorSolo':'No puede viajar un menor solo, tiene que ir con un acompa&ntilde;ante que no sea menor',
	'NecesitaSelecOrigen':'Necesita seleccionar un origen',
	'NecesitaSelecDestino':'Necesita seleccionar un destino',
	'ErrorOrigDestIguales':'Error: origen y destino iguales',
	'ElegirFechaValida':'Favor de Elegir una Fecha Valida',
	'FechaRegNoMenoraFechaSal':'La fecha de regreso no puede ser menor a la fecha de salida',
	'DebeSelecTipoPasajeroalMenos':'Debe seleccionar un tipo de pasajero cuando menos',
	'ElCampo':'El campo ',  //verificar linea 1088 validaciones
	'NoDebeContenerNum':'no debe contener numeros.',
	'DebeContenerSoloNum':'debe contener solo numeros',
	'NoTieneFormatoCorreo':'no contiene un formato de correo electr&oacute;nico.',  //verificar linea 1112 validaciones
	'Requerido':'Requerido',
	'IntroducSoloNumeros':'Introducir solo n&uacute;meros',
	'IntroducCorreoValido':'Introducir correo electr&oacute;nico v&aacute;lido',
	'NecesarioAceptTermCond':'Es necesario aceptar t&eacute;rminos y condiciones',
	'FaltaSeleccionar':'Falta seleccionar',
	'AsientosdeIda':'asiento(s) de ida',
	'AsientosdeRegreso':'asiento(s) de regreso',
	'FaltaNombrePasajero':'Falta nombre del pasajero',
	'FaltaCaptNomPasajero':'Falta capturar nombre del pasajero',
	'RSFaltaApPaternoPasajero':'Falta apellido paterno del pasajero',
	'RSFaltaCaptApPaternoPasajero':'Falta capturar apellido paterno del pasajero',
	'FaltaCaptPasaporte':'Falta capturar Visa del pasajero',
	'FaltaCapturarDomic':'Falta capturar la calle',
	'FaltaCapturarNumExt':'Falta capturar el n&uacute;mero exterior',
	'FaltaCapturarNumInt':'Falta capturar el n&uacute;mero interior',
	'FaltaCapturarDelMpio':'Falta capturar la delegaci&oacute;n o municipio',
	'FaltaCapturarEstado':'Falta capturar el estado',
	'FaltaCapturarCiudad':'Falta capturar la ciudad',
	'ErrorenCodPos':'Error en el Codigo Postal',
	'FaltaElegirPais':'Falta elegir pais',
	'ErrorenTelef':'Error en el telefono',
	'ErrorenEmail':'Error en el email',
	'ParaContinuarAceptTermCond':'Para continuar debes indicar que est&aacute;s de acuerdo con los t&eacute;rminos y condiciones de precio y viaje en la parte inferior de la pantalla.',
	'DebeSelecTipoPasajero':'Debe seleccionar el tipo de pasajero',
	'FavorSelecCorrida':'Favor de seleccionar una corrida',
	'CorridaRegNoPuedeSerSelec':'La corrida de Regreso no puede ser seleccionada, porque su fecha de Salida es menor a la fecha de Llegada de la corrida de Ida.',
	'NoPuedeSelecCorridaTraslapeconIda':'No es posible seleccionar esta corrida ya que se traslapa con la corrida de ida',
	'CantidadIncorrecta':'La cantidad introducida no es correcta',
	'SoloAceptaNumeros':'Solo se aceptan n&uacute;meros',
	'PasajerosYaFueronSelec':'Todos los Pasajeros ya fueron seleccionados',
	'TipoPagoInvalido':'Tipo de pago inv&aacute;lido',
	'NoComprasdeMasde20Pasaj':'No se puede hacer una compra de mas de 10 pasajeros',
	'MontoFichaNoPuedeSerCero':'El monto de la ficha no puede ser cero',
	'MontoFichaNoPuedeSerVacio':'El monto de la ficha no puede quedar vac&iacute;o',
	'DepositoNoPuedeSerMayoraVenta':'El dep&oacute;sito no puede ser mayor al saldo de venta',
	'FechaFinalNoMenoraInicial':'La fecha final no puede ser menor a la incial',
	'ElegirUsuarioparaContinuar':'Elegir un usuario para continuar.',
	'Enero':'Enero',
	'Febrero':'Febrero',
	'Marzo':'Marzo',
	'Abril':'Abril',
	'Mayo':'Mayo',
	'Junio':'Junio',
	'Julio':'Julio',
	'Agosto':'Agosto',
	'Septiembre':'Septiembre',
	'Octubre':'Octubre',
	'Noviembre':'Noviembre',
	'Diciembre':'Diciembre',
	'Lunes':'Lu',
	'Martes':'Ma',
	'Miercoles':'Mi',
	'Jueves':'Ju',
	'Viernes':'Vi',
	'Sabado':'Sa',
	'Domingo':'Do',
	'informacionreq':'Informaci&oacute;n requerida',
	'mensajecap':'ERROR: Debes Resolver el Captcha.',
	'RSNoPuedeSerMayorDe':'no puede ser mayor de',
	'RSNoPuedeSerMenorDe':'no puede ser menor de',
	'RSNoPuedeSerIgualA':'no puede ser igual a',
	'Eliminarultimopasajero':'No es posible eliminar el ultimo pasajero',
	'MensajeLogin':'Acceso exitoso',
	'NitNoViacia':'El numero NIT no debe quedar vac&iacute;o.',
	'IngreseDatos':'Ingresa los siguientes datos',
	'EsNecesarioLoguear':'Es necesario acceder con su cuenta de M&aacute;xima Distinci&oacute;n para continuar.',
	'NoEncontrado':' no se encontro coincidencia',
	'mensajecorreoduplicado':'Los correos de los pasajeros deben de ser distintos.',
	'usuariointercambio':'No se puede ingresar por que no corresponden los datos del pasajero con los de la cuenta.',
	'asientoSeleccion':'&#161;El asiento: $, Ya ha sido seleccionado por otro usuario&#33;',
	'asientoDisponible':'&#161;El asiento: $, No esta disponible&#33;',
	'diagramaLongitud':'&#161;El asiento: $, No existe en el Diagrama&#33;',
	'SesionVtaReq':'Es necesario que abra una sesi&oacute;n de venta para continuar.',
	'NoRestPasajero':'&#161;No se reconoce la siguiente restriccion $&#33;',
	'RestPasajeros':'&#161;El tipo de pasajero $ esta restringido para este canal de venta&#33;',
	'trnCorrIda':'&#161;No puedes seleccionar corrida de ida y transbordo de regreso&#33;',
	'trnCorrReg':'&#161;No puedes seleccionar transbordo de ida y corrida de regreso&#33;',
	'selTransCor':'&#161;Favor de seleccionar una opcion&#33;',
	'modificacionpasajeros':'Es necesario aceptar el cambio del Nombre para el pasajero 1',
	'selTipoSer':'&#161;Debes Seleccionar una Clase de Servicio&#33;',
	'favorSelecServicio':'&#161;Favor de Seleccionar un Tipo de Servicio&#33;',
	'FechaInterFinal':'&#161;La fecha de intercambiando no puede ser menor a la fecha de llegada&#33;',
	'FechaInterSalida':'&#161;La fecha de intercambiando no puede ser menor a la fecha de Salida&#33;',
	'CorridaInterSalida':'&#161;No puedes seleccionar esta corrida porque se traslapa con tu Salida&#33;',
	'CorridaInterLLegada':'&#161;No puedes seleccionar esta corrida porque se traslapa con tu Llegada&#33;',
	'msjBoletoAbierto':'No puedes seleccionar boletos abiertos para $!',
	'contMinimoTel':'&#161;El Campo debe contener al menos 10 digitos!',
	'tooltipMenor':'De 3 a 11 a&ntilde;os de edad',
	'tooltipInsen':'Descuento v&aacute;lido presentando credencial del INAPAM',
	'tooltipPCD':'Capacidades Diferentes',
	'tooltipPromocion':'Ingrese s&oacute;lo si tiene un c&oacute;digo de promoci&oacute;n',
	'opercionNoVacio':'No puede quedar vacio el N&uacute;mero de operaci&oacute;n',
	'nitNoVacio':'No puede quedar vacio el NIT',
    'tooltipCRM': 'Puedes ingresar con el correo que registraste en Mi viaje o Viaja m&aacute;s',
    'Memdup': 'Membres\u00EDa duplicada.',
    'Meminco': 'Membres\u00EDa capturada correctamente.',
    'DatosMemInc': 'Capture datos de membres\u00EDa correctamente.',
    'CapIDCRM': 'Capture el ID de Miembro.',
    'CapEmailCRM': 'Capture el correo.',
    'CapPassCRM': 'Capture la contrase\u00F1a.',
    'tooltipSeguros': 'Adquiere tu seguro para protegerte de cualquier imprevisto durante el viaje por $ MXN (IVA Incluido).',
    'tooltipSeguroslink': 'M\u00E1s informaci\u00F3n aqu\u00ED',
	'CapTarjeta': 'Falta capturar n&uacute;mero de tarjeta.',
	'CapCardVV': 'Falta capturar n&uacute;mero de seguridad.',
	'CapFechaExp': 'Falta capturar el mes de vencimiento.',
	'MesExpInvalido': 'Mes de vencimiento inv&aacute;lido.',
	'YearExpInvalido': 'Falta capturar el a&ntilde;o de vencimiento.',
	'CapNombreTH': 'Falta capturar el nombre del tarjetahabiente.',
	'CapApellidoTH': 'Falta capturar el apellido del tarjetahabiente.',
	'CapCorreoTH': 'Falta capturar el correo electr&oacute;nico del tarjetahabiente.',
	'CorreoTHInvalido': 'EL correo electr&oacute;nico del tarjetahabiente es incorrecto.'
};
// Dias de laSemana
var DiasSemanaES = new Array("Domingo", "Lunes", "Martes", "Mi\u00E9rcoles", "Jueves", "Viernes", "S\u00E1bado");
function RecuperaTxtES()
{
	return txtES;
}
function RecuperaMsjES()
{
	return msjES;
}
function RecupColumnasES()
{
	return ColumnasES;
}
function RecupPaisesES()
{
	return paisesES;
}
function RecupEstadoES()
{
	return estadoES;
}
function RecupDiasSemanaES() {
    return DiasSemanaES;
}
function DataTableES()
{
	return DataT_ES;
}
var DataT_ES = {
		"sProcessing":     "Procesando...",
		"sLengthMenu":     "Mostrar _MENU_ registros",
		"sZeroRecords":    "No se encontraron resultados",
		"sEmptyTable":     "Ningún dato disponible en esta tabla",
		"sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
		"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
		"sInfoFiltered":   "(Filtrado de un total de _MAX_ registros)",
		"sInfoPostFix":    "",
		"sSearch":         "Buscar:",
		"sInfoThousands":  ",",
		"sLoadingRecords": "Cargando...",
		"oPaginate": {
			"sFirst":    "Primero",
			"sLast":     "Último",
			"sNext":     "Siguiente",
			"sPrevious": "Anterior"
		},
		"oAria": {
			"sSortAscending":  ": Activar para ordenar la columna de manera asc",
			"sSortDescending": ": Activar para ordenar la columna de manera dsc"
		}
	};